name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.os }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run fmt check
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry & build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-


      - name: Shutdown services
        if: always()
        run: docker compose down -v

      - name: Start services
        run: docker compose up -d 

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h 127.0.0.1 -U payman && exit 0
            sleep 1
          done
          exit 1

      - name: Wait for mock PSP
        run: |
          for i in {1..30}; do
            curl -f http://127.0.0.1:9090/health && exit 0
            sleep 1
          done
          exit 1

      - name: Build
        run: cargo build --verbose

      - name: Wait for API
        run: |
          for i in {1..30}; do
            curl -f http://127.0.0.1:8080/health && exit 0
            sleep 1
          done
          echo "API not ready"
          exit 1

      - name: Run tests
        env:
          DATABASE_URL: postgres://payman:payman@127.0.0.1:5432/payman
          RUST_LOG: info
          MOCK_PSP_URL: http://127.0.0.1:9090
        run: make test